<a href="https://colab.research.google.com/github/jrg94/CSE5522/blob/lab1/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1.0**: Set up the environment. 

In [0]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

**1.1** Read the data from GitHub into a pandas dataframe. 

In [0]:
micro_rna_data_url = 'https://raw.githubusercontent.com/efosler/cse5522data/master/miRScore-x.csv'
micro_rna_dataframe = pd.read_csv(micro_rna_data_url, index_col=0) # Removes the index column
mrna_well_data_url = 'https://raw.githubusercontent.com/efosler/cse5522data/master/mRNA-y-well-explained.csv'
mrna_well_dataframe = pd.read_csv(mrna_well_data_url, index_col=0, header=None, skiprows=1).T
mrna_poor_data_url = 'https://raw.githubusercontent.com/efosler/cse5522data/master/mRNA-y-poor-explained.csv'
mrna_poor_dataframe = pd.read_csv(mrna_poor_data_url)
tissue_types_data_url = 'https://raw.githubusercontent.com/efosler/cse5522data/master/cancerType-x-Categorical.csv'
tissue_types_dataframe = pd.read_csv(tissue_types_data_url)

**1.2** Print out the top of the dataframe to make sure that the data loaded correctly.

In [256]:
micro_rna_dataframe.head()

MIRC1     MIRC2     MIRC3  ...    MIRC19    MIRC20    MIRC21
1  5.453767  4.383828  3.216983  ...  3.977328  5.501027  4.756962
2  4.321988  3.986583  3.829885  ...  4.199990  5.224254  4.429511
3  4.089116  4.178590  3.393789  ...  3.138479  5.682007  4.403253
4  4.884692  4.061140  3.475111  ...  4.542415  5.469924  4.693171
5  4.053976  4.224208  3.801616  ...  2.677879  5.577007  4.290140

[5 rows x 21 columns]

In [257]:
mrna_well_dataframe.head()

0  SNORD88B     GRHL2   C1orf172  ...      ST14    SHISA7      ELF3
1  3.321928  3.389608   5.822470  ...  6.207130  3.454255  3.575458
2  3.321928  3.586549   3.586549  ...  6.810804  3.586549  4.003557
3  3.321928  3.938521   3.993221  ...  5.812894  3.938521  4.369124
4  3.321928  3.794208   4.985892  ...  6.537319  4.534068  5.511952
5  3.321928  3.321928  11.037026  ...  6.029603  3.321928  3.545548

[5 rows x 35 columns]

In [258]:
mrna_poor_dataframe.head()

Unnamed: 0  TCGA.OR.A5J1.01  ...  TCGA.YZ.A984.01  TCGA.YZ.A985.01
0      NOBOX         3.321928  ...         3.321928         3.321928
1    SCGB1D4         3.321928  ...         3.321928         3.321928
2       RPL9         7.556077  ...         6.911874         8.355847
3     SPATA8         3.321928  ...         3.321928         3.321928
4    C2orf78         3.321928  ...         3.321928         3.321928

[5 rows x 8896 columns]

In [259]:
tissue_types_dataframe.head()

Unnamed: 0 cancerType
0           1        ACC
1           2        ACC
2           3        ACC
3           4        ACC
4           5        ACC

**1.3** Explore data shape

In [260]:
micro_rna_dataframe.shape

(8895, 21)

In [261]:
mrna_well_dataframe.shape

(8895, 35)

In [262]:
mrna_poor_dataframe.shape

(20, 8896)

In [263]:
tissue_types_dataframe.shape

(8895, 2)

**1.4** Explore data description

In [264]:
micro_rna_dataframe.describe()

MIRC1        MIRC2  ...       MIRC20       MIRC21
count  8895.000000  8895.000000  ...  8895.000000  8895.000000
mean      4.129920     4.765170  ...     5.445934     4.740501
std       1.099592     0.828207  ...     0.824836     0.775925
min       0.668085     1.305794  ...     1.428634     2.218998
25%       3.390396     4.331190  ...     5.119781     4.247824
50%       4.139365     4.829788  ...     5.482303     4.651004
75%       4.913180     5.327773  ...     5.900317     5.122929
max       7.923561     6.974327  ...     7.651443     7.945005

[8 rows x 21 columns]

In [287]:
mrna_well_dataframe.describe()

0          SNORD88B        GRHL2  ...       SHISA7         ELF3
count  8.895000e+03  8895.000000  ...  8895.000000  8895.000000
mean   3.321928e+00     8.155817  ...     4.015498    10.302955
std    3.286445e-13     3.178686  ...     1.584956     3.407289
min    3.321928e+00     3.321928  ...     3.321928     3.321928
25%    3.321928e+00     3.827169  ...     3.380293     8.762381
50%    3.321928e+00     9.721445  ...     3.487332    11.465436
75%    3.321928e+00    10.602422  ...     3.726068    12.869153
max    3.321928e+00    13.214960  ...    11.369453    15.908748

[8 rows x 35 columns]

**1.5** Import linear regression library from scikit. Borrowed parts of the analysis from an article written by [Nagesh Singh Chauhan](https://towardsdatascience.com/a-beginners-guide-to-linear-regression-in-python-with-scikit-learn-83a8f7ae2b4f).

In [0]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split 

**1.6** Setup x (microRNA features) and y (mRNA targets) values for regression. *Proof of concept*: let's try a single target value for now (SNORD88B).

In [286]:
x = micro_rna_dataframe.values
print(f'Micro RNA Features:\n {x}')
y = mrna_well_dataframe["SNORD88B"].values
print(f'mRNA Target Value SNORD88B:\n {y}')

Micro RNA Features:
 [[5.45376694 4.3838276  3.2169834  ... 3.97732759 5.50102704 4.75696249]
 [4.32198812 3.98658259 3.82988503 ... 4.19998992 5.22425381 4.42951072]
 [4.08911559 4.17859005 3.39378873 ... 3.1384791  5.68200738 4.40325252]
 ...
 [3.02645513 4.1710086  4.45773238 ... 2.69657029 4.73838707 5.70546468]
 [2.72775755 4.33952219 4.56746271 ... 3.01168894 5.60531597 5.87649015]
 [2.41979846 4.25275134 4.75874578 ... 2.74892305 5.13766053 6.12771056]]
mRNA Target Value SNORD88B:
 [3.32192809 3.32192809 3.32192809 ... 3.32192809 3.32192809 3.32192809]


**1.7** Split data 80/20 and run linear regression.

In [281]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)
r = LinearRegression()  
r.fit(x_train, y_train)
y_prediction = r.predict(x_test)
df = pd.DataFrame({'Actual': y_test, 'Predicted': y_prediction})
df.head()

Actual  Predicted
0  3.321928   3.321928
1  3.321928   3.321928
2  3.321928   3.321928
3  3.321928   3.321928
4  3.321928   3.321928

**1.8** Turns out SNORD88B is extremely stable. In other words, it's fairly easy to predict regardless of which features we choose. Let's try running this experiment for all target values.

